//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amica.Models.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Properties {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Amica.Models.Resources.Properties", typeof(Properties).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        public static string Deduction {
            get {
                return ResourceManager.GetString("Deduction", resourceCulture);
            }
        }
        
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string EnasarcoFund {
            get {
                return ResourceManager.GetString("EnasarcoFund", resourceCulture);
            }
        }
        
        public static string FiscalProfile {
            get {
                return ResourceManager.GetString("FiscalProfile", resourceCulture);
            }
        }
        
        public static string FreelanceFund {
            get {
                return ResourceManager.GetString("FreelanceFund", resourceCulture);
            }
        }
        
        public static string InpsReimbursement {
            get {
                return ResourceManager.GetString("InpsReimbursement", resourceCulture);
            }
        }
        
        public static string IsAdministrativeAccount {
            get {
                return ResourceManager.GetString("IsAdministrativeAccount", resourceCulture);
            }
        }
        
        public static string IsExclusiveAgent {
            get {
                return ResourceManager.GetString("IsExclusiveAgent", resourceCulture);
            }
        }
        
        public static string IsFreelance {
            get {
                return ResourceManager.GetString("IsFreelance", resourceCulture);
            }
        }
        
        public static string IsLegalEntity {
            get {
                return ResourceManager.GetString("IsLegalEntity", resourceCulture);
            }
        }
        
        public static string IsWelfareIncluded {
            get {
                return ResourceManager.GetString("IsWelfareIncluded", resourceCulture);
            }
        }
        
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        public static string REACode {
            get {
                return ResourceManager.GetString("REACode", resourceCulture);
            }
        }
        
        public static string SIACode {
            get {
                return ResourceManager.GetString("SIACode", resourceCulture);
            }
        }
        
        public static string TaxableShare {
            get {
                return ResourceManager.GetString("TaxableShare", resourceCulture);
            }
        }
        
        public static string TaxIdentificationNumber {
            get {
                return ResourceManager.GetString("TaxIdentificationNumber", resourceCulture);
            }
        }
        
        public static string UniqueId {
            get {
                return ResourceManager.GetString("UniqueId", resourceCulture);
            }
        }
        
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        public static string VatIdentificationNumber {
            get {
                return ResourceManager.GetString("VatIdentificationNumber", resourceCulture);
            }
        }
        
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        public static string MailSettings {
            get {
                return ResourceManager.GetString("MailSettings", resourceCulture);
            }
        }
        
        public static string IsIntraCommunity {
            get {
                return ResourceManager.GetString("IsIntraCommunity", resourceCulture);
            }
        }
        
        public static string IsSplitPayment {
            get {
                return ResourceManager.GetString("IsSplitPayment", resourceCulture);
            }
        }
        
        public static string IsVatExcluded {
            get {
                return ResourceManager.GetString("IsVatExcluded", resourceCulture);
            }
        }
        
        public static string MessageBody {
            get {
                return ResourceManager.GetString("MessageBody", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NonDeductible {
            get {
                return ResourceManager.GetString("NonDeductible", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        public static string SmptAddress {
            get {
                return ResourceManager.GetString("SmptAddress", resourceCulture);
            }
        }
        
        public static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        public static string TemplateSmptUsername {
            get {
                return ResourceManager.GetString("TemplateSmptUsername", resourceCulture);
            }
        }
        
        public static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
        
        public static string VatExemption {
            get {
                return ResourceManager.GetString("VatExemption", resourceCulture);
            }
        }
        
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        public static string PecMail {
            get {
                return ResourceManager.GetString("PecMail", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        public static string StateOrProvince {
            get {
                return ResourceManager.GetString("StateOrProvince", resourceCulture);
            }
        }
        
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        public static string TemplateMessageBody {
            get {
                return ResourceManager.GetString("TemplateMessageBody", resourceCulture);
            }
        }
        
        public static string TemplateMessageSubject {
            get {
                return ResourceManager.GetString("TemplateMessageSubject", resourceCulture);
            }
        }
        
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        public static string TemplateFromAddress {
            get {
                return ResourceManager.GetString("TemplateFromAddress", resourceCulture);
            }
        }
        
        public static string TemplateFromName {
            get {
                return ResourceManager.GetString("TemplateFromName", resourceCulture);
            }
        }
        
        public static string TemplateSmptPassword {
            get {
                return ResourceManager.GetString("TemplateSmptPassword", resourceCulture);
            }
        }
        
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        public static string AddressDescription {
            get {
                return ResourceManager.GetString("AddressDescription", resourceCulture);
            }
        }
        
        public static string CompanyNameDescription {
            get {
                return ResourceManager.GetString("CompanyNameDescription", resourceCulture);
            }
        }
        
        public static string FiscalProfileDescription {
            get {
                return ResourceManager.GetString("FiscalProfileDescription", resourceCulture);
            }
        }
        
        public static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        public static string PreferencesDescription {
            get {
                return ResourceManager.GetString("PreferencesDescription", resourceCulture);
            }
        }
        
        public static string VatIdentificationNumberPrompt {
            get {
                return ResourceManager.GetString("VatIdentificationNumberPrompt", resourceCulture);
            }
        }
    }
}
